[package]
name = "dll-syringe"
version = "0.1.3"
description = "A windows dll injection library written in rust."
readme = "README.md"
repository = "https://github.com/OpenByteDev/dll-syringe" 
homepage = "https://github.com/OpenByteDev/dll-syringe"
documentation = "https://docs.rs/dll-syringe"
license = "MIT"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2021"
categories = []
keywords = ["dll-injection", "dll", "inject", "windows"]

[dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "libloaderapi", "memoryapi", "wow64apiset"] }
cstr = "0.2"
sysinfo = "0.23"
widestring = "0.5"
rust_win32error = "0.8"
path-absolutize = "3.0"
dispose = "0.4"
stopwatch = "0.0"
quick-error = "2.0"
u16cstr = "0.3"

[target.'cfg(target_arch = "x86")'.dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
goblin = { version = "0.4", optional = true }

[features]
default = ["into_x86_from_x64"]
sync_send_syringe = []
into_x86_from_x64 = ["goblin"]
