cargo-features = ["edition2021"]

[package]
name = "dll-syringe"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "libloaderapi", "memoryapi", "wow64apiset"] }
cstr = "0.2"
wchar = "0.10"
sysinfo = "0.19"
widestring = "0.4"
rust_win32error = "0.8"
path-absolutize = "3.0"
dispose = "0.3"
stopwatch = "0.0"

[target.'cfg(target_arch = "x86")'.dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
goblin = { version = "0.4", optional = true }

[features]
default = ["into_x86_from_x64"]
into_x86_from_x64 = ["goblin"]
