[package]
name = "dll-syringe"
version = "0.3.0"
description = "A windows dll injection library written in rust."
readme = "README.md"
repository = "https://github.com/OpenByteDev/dll-syringe" 
homepage = "https://github.com/OpenByteDev/dll-syringe"
documentation = "https://docs.rs/dll-syringe"
license = "MIT"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2021"
categories = []
keywords = ["dll-injection", "dll", "inject", "windows"]

[dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "libloaderapi", "memoryapi", "wow64apiset"], default-features = false }
cstr = { version = "0.2", default-features = false }
sysinfo = { version = "0.23", default-features = false }
widestring = { version = "0.5", default-features = false }
rust_win32error = { version = "0.8", default-features = false }
path-absolutize = { version = "3.0", default-features = false }
stopwatch = { version = "0.0", default-features = false }
quick-error = { version = "2.0", default-features = false }
u16cstr = { version = "0.3", default-features = false }
iced-x86 = { version = "1.15", features = ["std", "code_asm"], default-features = false, optional = true }

[target.'cfg(target_arch = "x86")'.dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
goblin = { version = "0.4", optional = true, default-features = false, features = ["std", "pe32"] }

[dev-dependencies]
platforms = { version = "2.0", default-features = false }
dispose = { version = "0.4", default-features = false }

[features]
default = ["into_x86_from_x64", "call_remote_procedure"]
sync_send_syringe = []
into_x86_from_x64 = ["goblin"]
call_remote_procedure = ["iced-x86"]

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
