name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly for ${{ matrix.target }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
    steps:
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}

  test:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
    steps:
    - name: Test
      run: cargo test --verbose --target ${{ matrix.target }} -- --nocapture
