name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    name: Build & Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly (x86_64-pc-windows-msvc)
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true
    - name: Install latest nightly (i686-pc-windows-msvc)
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: i686-pc-windows-msvc
          override: true
    - name: Build (x86_64-pc-windows-msvc)
      run: cargo build --verbose --target=x86_64-pc-windows-msvc
    - name: Build (i686-pc-windows-msvc)
      run: cargo build --verbose --target=i686-pc-windows-msvc
    - name: Test (x86_64-pc-windows-msvc)
      run: cargo test --verbose --target=x86_64-pc-windows-msvc -- --nocapture
    - name: Test (i686-pc-windows-msvc)
      run: cargo test --verbose --target=i686-pc-windows-msvc -- --nocapture
