name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    name: Build & Test
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        target: ["i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly for ${{ matrix.target }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}
    - name: Test
      run: cargo test --verbose --target ${{ matrix.target }} -- --nocapture
